name: VCI directory audit action
categories:
on:
  schedule:
      - cron: '*/15 * * * *'
jobs:
  vci-directory-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
        node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run audit
  