name: VCI directory audit action
on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 12 * * *'
jobs:
  vci-directory-audit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build --if-present
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}

      
  